// Code generated by entc, DO NOT EDIT.

package bookreturn

const (
	// Label holds the string label denoting the bookreturn type in the database.
	Label = "bookreturn"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDEADLINE holds the string denoting the deadline field in the database.
	FieldDEADLINE = "deadline"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeLocation holds the string denoting the location edge name in mutations.
	EdgeLocation = "location"
	// EdgeMustreturn holds the string denoting the mustreturn edge name in mutations.
	EdgeMustreturn = "mustreturn"

	// Table holds the table name of the bookreturn in the database.
	Table = "bookreturns"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "bookreturns"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "USER_ID"
	// LocationTable is the table the holds the location relation/edge.
	LocationTable = "bookreturns"
	// LocationInverseTable is the table name for the Location entity.
	// It exists in this package in order to avoid circular dependency with the "location" package.
	LocationInverseTable = "locations"
	// LocationColumn is the table column denoting the location relation/edge.
	LocationColumn = "LOCATION_NAME"
	// MustreturnTable is the table the holds the mustreturn relation/edge.
	MustreturnTable = "bookreturns"
	// MustreturnInverseTable is the table name for the Bookborrow entity.
	// It exists in this package in order to avoid circular dependency with the "bookborrow" package.
	MustreturnInverseTable = "bookborrows"
	// MustreturnColumn is the table column denoting the mustreturn relation/edge.
	MustreturnColumn = "CLIENT_ID"
)

// Columns holds all SQL columns for bookreturn fields.
var Columns = []string{
	FieldID,
	FieldDEADLINE,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Bookreturn type.
var ForeignKeys = []string{
	"CLIENT_ID",
	"LOCATION_NAME",
	"USER_ID",
}
