// Code generated by entc, DO NOT EDIT.

package bookreturn

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team11/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// DEADLINE applies equality check predicate on the "DEADLINE" field. It's identical to DEADLINEEQ.
func DEADLINE(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDEADLINE), v))
	})
}

// DEADLINEEQ applies the EQ predicate on the "DEADLINE" field.
func DEADLINEEQ(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDEADLINE), v))
	})
}

// DEADLINENEQ applies the NEQ predicate on the "DEADLINE" field.
func DEADLINENEQ(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDEADLINE), v))
	})
}

// DEADLINEIn applies the In predicate on the "DEADLINE" field.
func DEADLINEIn(vs ...time.Time) predicate.Bookreturn {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bookreturn(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDEADLINE), v...))
	})
}

// DEADLINENotIn applies the NotIn predicate on the "DEADLINE" field.
func DEADLINENotIn(vs ...time.Time) predicate.Bookreturn {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bookreturn(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDEADLINE), v...))
	})
}

// DEADLINEGT applies the GT predicate on the "DEADLINE" field.
func DEADLINEGT(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDEADLINE), v))
	})
}

// DEADLINEGTE applies the GTE predicate on the "DEADLINE" field.
func DEADLINEGTE(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDEADLINE), v))
	})
}

// DEADLINELT applies the LT predicate on the "DEADLINE" field.
func DEADLINELT(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDEADLINE), v))
	})
}

// DEADLINELTE applies the LTE predicate on the "DEADLINE" field.
func DEADLINELTE(v time.Time) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDEADLINE), v))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocationTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Location) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocationInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMustreturn applies the HasEdge predicate on the "mustreturn" edge.
func HasMustreturn() predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MustreturnTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MustreturnTable, MustreturnColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMustreturnWith applies the HasEdge predicate on the "mustreturn" edge with a given conditions (other predicates).
func HasMustreturnWith(preds ...predicate.Bookborrow) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MustreturnInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MustreturnTable, MustreturnColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Bookreturn) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Bookreturn) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookreturn) predicate.Bookreturn {
	return predicate.Bookreturn(func(s *sql.Selector) {
		p(s.Not())
	})
}
