// Code generated by entc, DO NOT EDIT.

package researchtype

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team11/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// TYPENAME applies equality check predicate on the "TYPE_NAME" field. It's identical to TYPENAMEEQ.
func TYPENAME(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEEQ applies the EQ predicate on the "TYPE_NAME" field.
func TYPENAMEEQ(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMENEQ applies the NEQ predicate on the "TYPE_NAME" field.
func TYPENAMENEQ(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEIn applies the In predicate on the "TYPE_NAME" field.
func TYPENAMEIn(vs ...string) predicate.Researchtype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Researchtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTYPENAME), v...))
	})
}

// TYPENAMENotIn applies the NotIn predicate on the "TYPE_NAME" field.
func TYPENAMENotIn(vs ...string) predicate.Researchtype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Researchtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTYPENAME), v...))
	})
}

// TYPENAMEGT applies the GT predicate on the "TYPE_NAME" field.
func TYPENAMEGT(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEGTE applies the GTE predicate on the "TYPE_NAME" field.
func TYPENAMEGTE(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMELT applies the LT predicate on the "TYPE_NAME" field.
func TYPENAMELT(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMELTE applies the LTE predicate on the "TYPE_NAME" field.
func TYPENAMELTE(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEContains applies the Contains predicate on the "TYPE_NAME" field.
func TYPENAMEContains(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEHasPrefix applies the HasPrefix predicate on the "TYPE_NAME" field.
func TYPENAMEHasPrefix(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEHasSuffix applies the HasSuffix predicate on the "TYPE_NAME" field.
func TYPENAMEHasSuffix(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEEqualFold applies the EqualFold predicate on the "TYPE_NAME" field.
func TYPENAMEEqualFold(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTYPENAME), v))
	})
}

// TYPENAMEContainsFold applies the ContainsFold predicate on the "TYPE_NAME" field.
func TYPENAMEContainsFold(v string) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTYPENAME), v))
	})
}

// HasResearchType applies the HasEdge predicate on the "researchType" edge.
func HasResearchType() predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ResearchTypeTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResearchTypeTable, ResearchTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResearchTypeWith applies the HasEdge predicate on the "researchType" edge with a given conditions (other predicates).
func HasResearchTypeWith(preds ...predicate.Research) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ResearchTypeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResearchTypeTable, ResearchTypeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Researchtype) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Researchtype) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Researchtype) predicate.Researchtype {
	return predicate.Researchtype(func(s *sql.Selector) {
		p(s.Not())
	})
}
