// Code generated by entc, DO NOT EDIT.

package location

const (
	// Label holds the string label denoting the location type in the database.
	Label = "location"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLOCATIONNAME holds the string denoting the location_name field in the database.
	FieldLOCATIONNAME = "location_name"

	// EdgeReturnfrom holds the string denoting the returnfrom edge name in mutations.
	EdgeReturnfrom = "returnfrom"

	// Table holds the table name of the location in the database.
	Table = "locations"
	// ReturnfromTable is the table the holds the returnfrom relation/edge.
	ReturnfromTable = "bookreturns"
	// ReturnfromInverseTable is the table name for the Bookreturn entity.
	// It exists in this package in order to avoid circular dependency with the "bookreturn" package.
	ReturnfromInverseTable = "bookreturns"
	// ReturnfromColumn is the table column denoting the returnfrom relation/edge.
	ReturnfromColumn = "LOCATION_NAME"
)

// Columns holds all SQL columns for location fields.
var Columns = []string{
	FieldID,
	FieldLOCATIONNAME,
}

var (
	// LOCATIONNAMEValidator is a validator for the "LOCATION_NAME" field. It is called by the builders before save.
	LOCATIONNAMEValidator func(string) error
)
