// Code generated by entc, DO NOT EDIT.

package roominfo

const (
	// Label holds the string label denoting the roominfo type in the database.
	Label = "roominfo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomID holds the string denoting the roomid field in the database.
	FieldRoomID = "room_id"
	// FieldRoomNo holds the string denoting the roomno field in the database.
	FieldRoomNo = "room_no"
	// FieldRoomType holds the string denoting the roomtype field in the database.
	FieldRoomType = "room_type"
	// FieldRoomTime holds the string denoting the roomtime field in the database.
	FieldRoomTime = "room_time"
	// FieldRoomStatus holds the string denoting the roomstatus field in the database.
	FieldRoomStatus = "room_status"

	// EdgePreemption holds the string denoting the preemption edge name in mutations.
	EdgePreemption = "preemption"

	// Table holds the table name of the roominfo in the database.
	Table = "roominfos"
	// PreemptionTable is the table the holds the preemption relation/edge.
	PreemptionTable = "preemptions"
	// PreemptionInverseTable is the table name for the Preemption entity.
	// It exists in this package in order to avoid circular dependency with the "preemption" package.
	PreemptionInverseTable = "preemptions"
	// PreemptionColumn is the table column denoting the preemption relation/edge.
	PreemptionColumn = "RoomID"
)

// Columns holds all SQL columns for roominfo fields.
var Columns = []string{
	FieldID,
	FieldRoomID,
	FieldRoomNo,
	FieldRoomType,
	FieldRoomTime,
	FieldRoomStatus,
}

var (
	// RoomNoValidator is a validator for the "RoomNo" field. It is called by the builders before save.
	RoomNoValidator func(string) error
	// RoomTypeValidator is a validator for the "RoomType" field. It is called by the builders before save.
	RoomTypeValidator func(string) error
	// RoomTimeValidator is a validator for the "RoomTime" field. It is called by the builders before save.
	RoomTimeValidator func(string) error
	// RoomStatusValidator is a validator for the "RoomStatus" field. It is called by the builders before save.
	RoomStatusValidator func(string) error
)
