// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team11/app/ent/bookreturn"
	"github.com/team11/app/ent/predicate"
)

// BookreturnUpdate is the builder for updating Bookreturn entities.
type BookreturnUpdate struct {
	config
	hooks      []Hook
	mutation   *BookreturnMutation
	predicates []predicate.Bookreturn
}

// Where adds a new predicate for the builder.
func (bu *BookreturnUpdate) Where(ps ...predicate.Bookreturn) *BookreturnUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetBookName sets the book_name field.
func (bu *BookreturnUpdate) SetBookName(s string) *BookreturnUpdate {
	bu.mutation.SetBookName(s)
	return bu
}

// Mutation returns the BookreturnMutation object of the builder.
func (bu *BookreturnUpdate) Mutation() *BookreturnMutation {
	return bu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BookreturnUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := bu.mutation.BookName(); ok {
		if err := bookreturn.BookNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "book_name", err: fmt.Errorf("ent: validator failed for field \"book_name\": %w", err)}
		}
	}
	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookreturnMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookreturnUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookreturnUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookreturnUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BookreturnUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bookreturn.Table,
			Columns: bookreturn.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bookreturn.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.BookName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bookreturn.FieldBookName,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookreturn.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BookreturnUpdateOne is the builder for updating a single Bookreturn entity.
type BookreturnUpdateOne struct {
	config
	hooks    []Hook
	mutation *BookreturnMutation
}

// SetBookName sets the book_name field.
func (buo *BookreturnUpdateOne) SetBookName(s string) *BookreturnUpdateOne {
	buo.mutation.SetBookName(s)
	return buo
}

// Mutation returns the BookreturnMutation object of the builder.
func (buo *BookreturnUpdateOne) Mutation() *BookreturnMutation {
	return buo.mutation
}

// Save executes the query and returns the updated entity.
func (buo *BookreturnUpdateOne) Save(ctx context.Context) (*Bookreturn, error) {
	if v, ok := buo.mutation.BookName(); ok {
		if err := bookreturn.BookNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "book_name", err: fmt.Errorf("ent: validator failed for field \"book_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Bookreturn
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookreturnMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookreturnUpdateOne) SaveX(ctx context.Context) *Bookreturn {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BookreturnUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookreturnUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BookreturnUpdateOne) sqlSave(ctx context.Context) (b *Bookreturn, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bookreturn.Table,
			Columns: bookreturn.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bookreturn.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Bookreturn.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := buo.mutation.BookName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bookreturn.FieldBookName,
		})
	}
	b = &Bookreturn{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookreturn.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
