// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team11/app/ent/cliententity"
	"github.com/team11/app/ent/predicate"
)

// ClientEntityDelete is the builder for deleting a ClientEntity entity.
type ClientEntityDelete struct {
	config
	hooks      []Hook
	mutation   *ClientEntityMutation
	predicates []predicate.ClientEntity
}

// Where adds a new predicate to the delete builder.
func (ced *ClientEntityDelete) Where(ps ...predicate.ClientEntity) *ClientEntityDelete {
	ced.predicates = append(ced.predicates, ps...)
	return ced
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ced *ClientEntityDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ced.hooks) == 0 {
		affected, err = ced.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClientEntityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ced.mutation = mutation
			affected, err = ced.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ced.hooks) - 1; i >= 0; i-- {
			mut = ced.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ced.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ced *ClientEntityDelete) ExecX(ctx context.Context) int {
	n, err := ced.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ced *ClientEntityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: cliententity.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cliententity.FieldID,
			},
		},
	}
	if ps := ced.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ced.driver, _spec)
}

// ClientEntityDeleteOne is the builder for deleting a single ClientEntity entity.
type ClientEntityDeleteOne struct {
	ced *ClientEntityDelete
}

// Exec executes the deletion query.
func (cedo *ClientEntityDeleteOne) Exec(ctx context.Context) error {
	n, err := cedo.ced.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cliententity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cedo *ClientEntityDeleteOne) ExecX(ctx context.Context) {
	cedo.ced.ExecX(ctx)
}
