// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/team11/app/ent/cliententity"
	"github.com/team11/app/ent/status"
)

// ClientEntity is the model entity for the ClientEntity schema.
type ClientEntity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CLIENTNAME holds the value of the "CLIENT_NAME" field.
	CLIENTNAME string `json:"CLIENT_NAME,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClientEntityQuery when eager-loading is set.
	Edges     ClientEntityEdges `json:"edges"`
	STATUS_ID *int
}

// ClientEntityEdges holds the relations/edges for other nodes in the graph.
type ClientEntityEdges struct {
	// Booked holds the value of the booked edge.
	Booked []*Booking
	// State holds the value of the state edge.
	State *Status
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BookedOrErr returns the Booked value or an error if the edge
// was not loaded in eager-loading.
func (e ClientEntityEdges) BookedOrErr() ([]*Booking, error) {
	if e.loadedTypes[0] {
		return e.Booked, nil
	}
	return nil, &NotLoadedError{edge: "booked"}
}

// StateOrErr returns the State value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClientEntityEdges) StateOrErr() (*Status, error) {
	if e.loadedTypes[1] {
		if e.State == nil {
			// The edge state was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: status.Label}
		}
		return e.State, nil
	}
	return nil, &NotLoadedError{edge: "state"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClientEntity) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // CLIENT_NAME
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*ClientEntity) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // STATUS_ID
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClientEntity fields.
func (ce *ClientEntity) assignValues(values ...interface{}) error {
	if m, n := len(values), len(cliententity.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ce.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field CLIENT_NAME", values[0])
	} else if value.Valid {
		ce.CLIENTNAME = value.String
	}
	values = values[1:]
	if len(values) == len(cliententity.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field STATUS_ID", value)
		} else if value.Valid {
			ce.STATUS_ID = new(int)
			*ce.STATUS_ID = int(value.Int64)
		}
	}
	return nil
}

// QueryBooked queries the booked edge of the ClientEntity.
func (ce *ClientEntity) QueryBooked() *BookingQuery {
	return (&ClientEntityClient{config: ce.config}).QueryBooked(ce)
}

// QueryState queries the state edge of the ClientEntity.
func (ce *ClientEntity) QueryState() *StatusQuery {
	return (&ClientEntityClient{config: ce.config}).QueryState(ce)
}

// Update returns a builder for updating this ClientEntity.
// Note that, you need to call ClientEntity.Unwrap() before calling this method, if this ClientEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (ce *ClientEntity) Update() *ClientEntityUpdateOne {
	return (&ClientEntityClient{config: ce.config}).UpdateOne(ce)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ce *ClientEntity) Unwrap() *ClientEntity {
	tx, ok := ce.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClientEntity is not a transactional entity")
	}
	ce.config.driver = tx.drv
	return ce
}

// String implements the fmt.Stringer.
func (ce *ClientEntity) String() string {
	var builder strings.Builder
	builder.WriteString("ClientEntity(")
	builder.WriteString(fmt.Sprintf("id=%v", ce.ID))
	builder.WriteString(", CLIENT_NAME=")
	builder.WriteString(ce.CLIENTNAME)
	builder.WriteByte(')')
	return builder.String()
}

// ClientEntities is a parsable slice of ClientEntity.
type ClientEntities []*ClientEntity

func (ce ClientEntities) config(cfg config) {
	for _i := range ce {
		ce[_i].config = cfg
	}
}
