// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team11/app/ent/book"
	"github.com/team11/app/ent/bookborrow"
	"github.com/team11/app/ent/booking"
	"github.com/team11/app/ent/bookreturn"
	"github.com/team11/app/ent/predicate"
	"github.com/team11/app/ent/preemption"
	"github.com/team11/app/ent/research"
	"github.com/team11/app/ent/role"
	"github.com/team11/app/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks      []Hook
	mutation   *UserMutation
	predicates []predicate.User
}

// Where adds a new predicate for the builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.predicates = append(uu.predicates, ps...)
	return uu
}

// SetUSEREMAIL sets the USER_EMAIL field.
func (uu *UserUpdate) SetUSEREMAIL(s string) *UserUpdate {
	uu.mutation.SetUSEREMAIL(s)
	return uu
}

// SetUSERNAME sets the USER_NAME field.
func (uu *UserUpdate) SetUSERNAME(s string) *UserUpdate {
	uu.mutation.SetUSERNAME(s)
	return uu
}

// SetPASSWORD sets the PASSWORD field.
func (uu *UserUpdate) SetPASSWORD(s string) *UserUpdate {
	uu.mutation.SetPASSWORD(s)
	return uu
}

// SetPositionID sets the position edge to Role by id.
func (uu *UserUpdate) SetPositionID(id int) *UserUpdate {
	uu.mutation.SetPositionID(id)
	return uu
}

// SetNillablePositionID sets the position edge to Role by id if the given value is not nil.
func (uu *UserUpdate) SetNillablePositionID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetPositionID(*id)
	}
	return uu
}

// SetPosition sets the position edge to Role.
func (uu *UserUpdate) SetPosition(r *Role) *UserUpdate {
	return uu.SetPositionID(r.ID)
}

// AddBookingIDs adds the booking edge to Booking by ids.
func (uu *UserUpdate) AddBookingIDs(ids ...int) *UserUpdate {
	uu.mutation.AddBookingIDs(ids...)
	return uu
}

// AddBooking adds the booking edges to Booking.
func (uu *UserUpdate) AddBooking(b ...*Booking) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.AddBookingIDs(ids...)
}

// AddAddbyIDs adds the addby edge to Book by ids.
func (uu *UserUpdate) AddAddbyIDs(ids ...int) *UserUpdate {
	uu.mutation.AddAddbyIDs(ids...)
	return uu
}

// AddAddby adds the addby edges to Book.
func (uu *UserUpdate) AddAddby(b ...*Book) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.AddAddbyIDs(ids...)
}

// AddBorrowIDs adds the borrow edge to Bookborrow by ids.
func (uu *UserUpdate) AddBorrowIDs(ids ...int) *UserUpdate {
	uu.mutation.AddBorrowIDs(ids...)
	return uu
}

// AddBorrow adds the borrow edges to Bookborrow.
func (uu *UserUpdate) AddBorrow(b ...*Bookborrow) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.AddBorrowIDs(ids...)
}

// AddPreemptionIDs adds the preemption edge to Preemption by ids.
func (uu *UserUpdate) AddPreemptionIDs(ids ...int) *UserUpdate {
	uu.mutation.AddPreemptionIDs(ids...)
	return uu
}

// AddPreemption adds the preemption edges to Preemption.
func (uu *UserUpdate) AddPreemption(p ...*Preemption) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.AddPreemptionIDs(ids...)
}

// AddRecordIDs adds the record edge to Research by ids.
func (uu *UserUpdate) AddRecordIDs(ids ...int) *UserUpdate {
	uu.mutation.AddRecordIDs(ids...)
	return uu
}

// AddRecord adds the record edges to Research.
func (uu *UserUpdate) AddRecord(r ...*Research) *UserUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uu.AddRecordIDs(ids...)
}

// AddReturnIDs adds the return edge to Bookreturn by ids.
func (uu *UserUpdate) AddReturnIDs(ids ...int) *UserUpdate {
	uu.mutation.AddReturnIDs(ids...)
	return uu
}

// AddReturn adds the return edges to Bookreturn.
func (uu *UserUpdate) AddReturn(b ...*Bookreturn) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.AddReturnIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearPosition clears the position edge to Role.
func (uu *UserUpdate) ClearPosition() *UserUpdate {
	uu.mutation.ClearPosition()
	return uu
}

// RemoveBookingIDs removes the booking edge to Booking by ids.
func (uu *UserUpdate) RemoveBookingIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveBookingIDs(ids...)
	return uu
}

// RemoveBooking removes booking edges to Booking.
func (uu *UserUpdate) RemoveBooking(b ...*Booking) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.RemoveBookingIDs(ids...)
}

// RemoveAddbyIDs removes the addby edge to Book by ids.
func (uu *UserUpdate) RemoveAddbyIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveAddbyIDs(ids...)
	return uu
}

// RemoveAddby removes addby edges to Book.
func (uu *UserUpdate) RemoveAddby(b ...*Book) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.RemoveAddbyIDs(ids...)
}

// RemoveBorrowIDs removes the borrow edge to Bookborrow by ids.
func (uu *UserUpdate) RemoveBorrowIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveBorrowIDs(ids...)
	return uu
}

// RemoveBorrow removes borrow edges to Bookborrow.
func (uu *UserUpdate) RemoveBorrow(b ...*Bookborrow) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.RemoveBorrowIDs(ids...)
}

// RemovePreemptionIDs removes the preemption edge to Preemption by ids.
func (uu *UserUpdate) RemovePreemptionIDs(ids ...int) *UserUpdate {
	uu.mutation.RemovePreemptionIDs(ids...)
	return uu
}

// RemovePreemption removes preemption edges to Preemption.
func (uu *UserUpdate) RemovePreemption(p ...*Preemption) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.RemovePreemptionIDs(ids...)
}

// RemoveRecordIDs removes the record edge to Research by ids.
func (uu *UserUpdate) RemoveRecordIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveRecordIDs(ids...)
	return uu
}

// RemoveRecord removes record edges to Research.
func (uu *UserUpdate) RemoveRecord(r ...*Research) *UserUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uu.RemoveRecordIDs(ids...)
}

// RemoveReturnIDs removes the return edge to Bookreturn by ids.
func (uu *UserUpdate) RemoveReturnIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveReturnIDs(ids...)
	return uu
}

// RemoveReturn removes return edges to Bookreturn.
func (uu *UserUpdate) RemoveReturn(b ...*Bookreturn) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.RemoveReturnIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := uu.mutation.USEREMAIL(); ok {
		if err := user.USEREMAILValidator(v); err != nil {
			return 0, &ValidationError{Name: "USER_EMAIL", err: fmt.Errorf("ent: validator failed for field \"USER_EMAIL\": %w", err)}
		}
	}
	if v, ok := uu.mutation.USERNAME(); ok {
		if err := user.USERNAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "USER_NAME", err: fmt.Errorf("ent: validator failed for field \"USER_NAME\": %w", err)}
		}
	}
	if v, ok := uu.mutation.PASSWORD(); ok {
		if err := user.PASSWORDValidator(v); err != nil {
			return 0, &ValidationError{Name: "PASSWORD", err: fmt.Errorf("ent: validator failed for field \"PASSWORD\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(uu.hooks) == 0 {
		affected, err = uu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uu.mutation = mutation
			affected, err = uu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uu.hooks) - 1; i >= 0; i-- {
			mut = uu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	if ps := uu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.USEREMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSEREMAIL,
		})
	}
	if value, ok := uu.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSERNAME,
		})
	}
	if value, ok := uu.mutation.PASSWORD(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldPASSWORD,
		})
	}
	if uu.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.PositionTable,
			Columns: []string{user.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.PositionTable,
			Columns: []string{user.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uu.mutation.RemovedBookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingTable,
			Columns: []string{user.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.BookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingTable,
			Columns: []string{user.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uu.mutation.RemovedAddbyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AddbyTable,
			Columns: []string{user.AddbyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.AddbyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AddbyTable,
			Columns: []string{user.AddbyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uu.mutation.RemovedBorrowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BorrowTable,
			Columns: []string{user.BorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.BorrowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BorrowTable,
			Columns: []string{user.BorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uu.mutation.RemovedPreemptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PreemptionTable,
			Columns: []string{user.PreemptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: preemption.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.PreemptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PreemptionTable,
			Columns: []string{user.PreemptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: preemption.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uu.mutation.RemovedRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecordTable,
			Columns: []string{user.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: research.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecordTable,
			Columns: []string{user.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: research.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uu.mutation.RemovedReturnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReturnTable,
			Columns: []string{user.ReturnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookreturn.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.ReturnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReturnTable,
			Columns: []string{user.ReturnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookreturn.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// SetUSEREMAIL sets the USER_EMAIL field.
func (uuo *UserUpdateOne) SetUSEREMAIL(s string) *UserUpdateOne {
	uuo.mutation.SetUSEREMAIL(s)
	return uuo
}

// SetUSERNAME sets the USER_NAME field.
func (uuo *UserUpdateOne) SetUSERNAME(s string) *UserUpdateOne {
	uuo.mutation.SetUSERNAME(s)
	return uuo
}

// SetPASSWORD sets the PASSWORD field.
func (uuo *UserUpdateOne) SetPASSWORD(s string) *UserUpdateOne {
	uuo.mutation.SetPASSWORD(s)
	return uuo
}

// SetPositionID sets the position edge to Role by id.
func (uuo *UserUpdateOne) SetPositionID(id int) *UserUpdateOne {
	uuo.mutation.SetPositionID(id)
	return uuo
}

// SetNillablePositionID sets the position edge to Role by id if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePositionID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetPositionID(*id)
	}
	return uuo
}

// SetPosition sets the position edge to Role.
func (uuo *UserUpdateOne) SetPosition(r *Role) *UserUpdateOne {
	return uuo.SetPositionID(r.ID)
}

// AddBookingIDs adds the booking edge to Booking by ids.
func (uuo *UserUpdateOne) AddBookingIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddBookingIDs(ids...)
	return uuo
}

// AddBooking adds the booking edges to Booking.
func (uuo *UserUpdateOne) AddBooking(b ...*Booking) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.AddBookingIDs(ids...)
}

// AddAddbyIDs adds the addby edge to Book by ids.
func (uuo *UserUpdateOne) AddAddbyIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddAddbyIDs(ids...)
	return uuo
}

// AddAddby adds the addby edges to Book.
func (uuo *UserUpdateOne) AddAddby(b ...*Book) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.AddAddbyIDs(ids...)
}

// AddBorrowIDs adds the borrow edge to Bookborrow by ids.
func (uuo *UserUpdateOne) AddBorrowIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddBorrowIDs(ids...)
	return uuo
}

// AddBorrow adds the borrow edges to Bookborrow.
func (uuo *UserUpdateOne) AddBorrow(b ...*Bookborrow) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.AddBorrowIDs(ids...)
}

// AddPreemptionIDs adds the preemption edge to Preemption by ids.
func (uuo *UserUpdateOne) AddPreemptionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddPreemptionIDs(ids...)
	return uuo
}

// AddPreemption adds the preemption edges to Preemption.
func (uuo *UserUpdateOne) AddPreemption(p ...*Preemption) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.AddPreemptionIDs(ids...)
}

// AddRecordIDs adds the record edge to Research by ids.
func (uuo *UserUpdateOne) AddRecordIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddRecordIDs(ids...)
	return uuo
}

// AddRecord adds the record edges to Research.
func (uuo *UserUpdateOne) AddRecord(r ...*Research) *UserUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uuo.AddRecordIDs(ids...)
}

// AddReturnIDs adds the return edge to Bookreturn by ids.
func (uuo *UserUpdateOne) AddReturnIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddReturnIDs(ids...)
	return uuo
}

// AddReturn adds the return edges to Bookreturn.
func (uuo *UserUpdateOne) AddReturn(b ...*Bookreturn) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.AddReturnIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearPosition clears the position edge to Role.
func (uuo *UserUpdateOne) ClearPosition() *UserUpdateOne {
	uuo.mutation.ClearPosition()
	return uuo
}

// RemoveBookingIDs removes the booking edge to Booking by ids.
func (uuo *UserUpdateOne) RemoveBookingIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveBookingIDs(ids...)
	return uuo
}

// RemoveBooking removes booking edges to Booking.
func (uuo *UserUpdateOne) RemoveBooking(b ...*Booking) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.RemoveBookingIDs(ids...)
}

// RemoveAddbyIDs removes the addby edge to Book by ids.
func (uuo *UserUpdateOne) RemoveAddbyIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveAddbyIDs(ids...)
	return uuo
}

// RemoveAddby removes addby edges to Book.
func (uuo *UserUpdateOne) RemoveAddby(b ...*Book) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.RemoveAddbyIDs(ids...)
}

// RemoveBorrowIDs removes the borrow edge to Bookborrow by ids.
func (uuo *UserUpdateOne) RemoveBorrowIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveBorrowIDs(ids...)
	return uuo
}

// RemoveBorrow removes borrow edges to Bookborrow.
func (uuo *UserUpdateOne) RemoveBorrow(b ...*Bookborrow) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.RemoveBorrowIDs(ids...)
}

// RemovePreemptionIDs removes the preemption edge to Preemption by ids.
func (uuo *UserUpdateOne) RemovePreemptionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemovePreemptionIDs(ids...)
	return uuo
}

// RemovePreemption removes preemption edges to Preemption.
func (uuo *UserUpdateOne) RemovePreemption(p ...*Preemption) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.RemovePreemptionIDs(ids...)
}

// RemoveRecordIDs removes the record edge to Research by ids.
func (uuo *UserUpdateOne) RemoveRecordIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveRecordIDs(ids...)
	return uuo
}

// RemoveRecord removes record edges to Research.
func (uuo *UserUpdateOne) RemoveRecord(r ...*Research) *UserUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uuo.RemoveRecordIDs(ids...)
}

// RemoveReturnIDs removes the return edge to Bookreturn by ids.
func (uuo *UserUpdateOne) RemoveReturnIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveReturnIDs(ids...)
	return uuo
}

// RemoveReturn removes return edges to Bookreturn.
func (uuo *UserUpdateOne) RemoveReturn(b ...*Bookreturn) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.RemoveReturnIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	if v, ok := uuo.mutation.USEREMAIL(); ok {
		if err := user.USEREMAILValidator(v); err != nil {
			return nil, &ValidationError{Name: "USER_EMAIL", err: fmt.Errorf("ent: validator failed for field \"USER_EMAIL\": %w", err)}
		}
	}
	if v, ok := uuo.mutation.USERNAME(); ok {
		if err := user.USERNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "USER_NAME", err: fmt.Errorf("ent: validator failed for field \"USER_NAME\": %w", err)}
		}
	}
	if v, ok := uuo.mutation.PASSWORD(); ok {
		if err := user.PASSWORDValidator(v); err != nil {
			return nil, &ValidationError{Name: "PASSWORD", err: fmt.Errorf("ent: validator failed for field \"PASSWORD\": %w", err)}
		}
	}

	var (
		err  error
		node *User
	)
	if len(uuo.hooks) == 0 {
		node, err = uuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uuo.mutation = mutation
			node, err = uuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuo.hooks) - 1; i >= 0; i-- {
			mut = uuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	u, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return u
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (u *User, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing User.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := uuo.mutation.USEREMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSEREMAIL,
		})
	}
	if value, ok := uuo.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSERNAME,
		})
	}
	if value, ok := uuo.mutation.PASSWORD(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldPASSWORD,
		})
	}
	if uuo.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.PositionTable,
			Columns: []string{user.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.PositionTable,
			Columns: []string{user.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uuo.mutation.RemovedBookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingTable,
			Columns: []string{user.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.BookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingTable,
			Columns: []string{user.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uuo.mutation.RemovedAddbyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AddbyTable,
			Columns: []string{user.AddbyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.AddbyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AddbyTable,
			Columns: []string{user.AddbyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uuo.mutation.RemovedBorrowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BorrowTable,
			Columns: []string{user.BorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.BorrowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BorrowTable,
			Columns: []string{user.BorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uuo.mutation.RemovedPreemptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PreemptionTable,
			Columns: []string{user.PreemptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: preemption.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.PreemptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PreemptionTable,
			Columns: []string{user.PreemptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: preemption.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uuo.mutation.RemovedRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecordTable,
			Columns: []string{user.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: research.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecordTable,
			Columns: []string{user.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: research.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := uuo.mutation.RemovedReturnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReturnTable,
			Columns: []string{user.ReturnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookreturn.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.ReturnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReturnTable,
			Columns: []string{user.ReturnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookreturn.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	u = &User{config: uuo.config}
	_spec.Assign = u.assignValues
	_spec.ScanValues = u.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return u, nil
}
