// Code generated by entc, DO NOT EDIT.

package booking

import (
	"time"
)

const (
	// Label holds the string label denoting the booking type in the database.
	Label = "booking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBOOKINGDATE holds the string denoting the booking_date field in the database.
	FieldBOOKINGDATE = "booking_date"
	// FieldTIMELEFT holds the string denoting the time_left field in the database.
	FieldTIMELEFT = "time_left"
	// FieldUSERNUMBER holds the string denoting the user_number field in the database.
	FieldUSERNUMBER = "user_number"
	// FieldBORROWITEM holds the string denoting the borrow_item field in the database.
	FieldBORROWITEM = "borrow_item"
	// FieldPHONENUMBER holds the string denoting the phone_number field in the database.
	FieldPHONENUMBER = "phone_number"

	// EdgeUsedby holds the string denoting the usedby edge name in mutations.
	EdgeUsedby = "usedby"
	// EdgeGetservice holds the string denoting the getservice edge name in mutations.
	EdgeGetservice = "getservice"
	// EdgeUsing holds the string denoting the using edge name in mutations.
	EdgeUsing = "using"

	// Table holds the table name of the booking in the database.
	Table = "bookings"
	// UsedbyTable is the table the holds the usedby relation/edge.
	UsedbyTable = "bookings"
	// UsedbyInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsedbyInverseTable = "users"
	// UsedbyColumn is the table column denoting the usedby relation/edge.
	UsedbyColumn = "USER_ID"
	// GetserviceTable is the table the holds the getservice relation/edge.
	GetserviceTable = "bookings"
	// GetserviceInverseTable is the table name for the ServicePoint entity.
	// It exists in this package in order to avoid circular dependency with the "servicepoint" package.
	GetserviceInverseTable = "service_points"
	// GetserviceColumn is the table column denoting the getservice relation/edge.
	GetserviceColumn = "SERVICEPOINT_ID"
	// UsingTable is the table the holds the using relation/edge.
	UsingTable = "bookings"
	// UsingInverseTable is the table name for the ClientEntity entity.
	// It exists in this package in order to avoid circular dependency with the "cliententity" package.
	UsingInverseTable = "client_entities"
	// UsingColumn is the table column denoting the using relation/edge.
	UsingColumn = "CLIENT_ID"
)

// Columns holds all SQL columns for booking fields.
var Columns = []string{
	FieldID,
	FieldBOOKINGDATE,
	FieldTIMELEFT,
	FieldUSERNUMBER,
	FieldBORROWITEM,
	FieldPHONENUMBER,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Booking type.
var ForeignKeys = []string{
	"CLIENT_ID",
	"SERVICEPOINT_ID",
	"USER_ID",
}

var (
	// DefaultBOOKINGDATE holds the default value on creation for the BOOKING_DATE field.
	DefaultBOOKINGDATE func() time.Time
	// USERNUMBERValidator is a validator for the "USER_NUMBER" field. It is called by the builders before save.
	USERNUMBERValidator func(int) error
	// BORROWITEMValidator is a validator for the "BORROW_ITEM" field. It is called by the builders before save.
	BORROWITEMValidator func(int) error
	// PHONENUMBERValidator is a validator for the "PHONE_NUMBER" field. It is called by the builders before save.
	PHONENUMBERValidator func(string) error
)
