// Code generated by entc, DO NOT EDIT.

package category

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCategoryName holds the string denoting the categoryname field in the database.
	FieldCategoryName = "category_name"

	// EdgeCatof holds the string denoting the catof edge name in mutations.
	EdgeCatof = "catof"

	// Table holds the table name of the category in the database.
	Table = "categories"
	// CatofTable is the table the holds the catof relation/edge.
	CatofTable = "books"
	// CatofInverseTable is the table name for the Book entity.
	// It exists in this package in order to avoid circular dependency with the "book" package.
	CatofInverseTable = "books"
	// CatofColumn is the table column denoting the catof relation/edge.
	CatofColumn = "Category_id"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldCategoryName,
}

var (
	// CategoryNameValidator is a validator for the "CategoryName" field. It is called by the builders before save.
	CategoryNameValidator func(string) error
)
