// Code generated by entc, DO NOT EDIT.

package servicepoint

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team11/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// COUNTERNUMBER applies equality check predicate on the "COUNTER_NUMBER" field. It's identical to COUNTERNUMBEREQ.
func COUNTERNUMBER(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBEREQ applies the EQ predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBEREQ(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERNEQ applies the NEQ predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERNEQ(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERIn applies the In predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERIn(vs ...string) predicate.ServicePoint {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ServicePoint(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCOUNTERNUMBER), v...))
	})
}

// COUNTERNUMBERNotIn applies the NotIn predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERNotIn(vs ...string) predicate.ServicePoint {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ServicePoint(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCOUNTERNUMBER), v...))
	})
}

// COUNTERNUMBERGT applies the GT predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERGT(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERGTE applies the GTE predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERGTE(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERLT applies the LT predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERLT(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERLTE applies the LTE predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERLTE(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERContains applies the Contains predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERContains(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERHasPrefix applies the HasPrefix predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERHasPrefix(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERHasSuffix applies the HasSuffix predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERHasSuffix(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBEREqualFold applies the EqualFold predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBEREqualFold(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCOUNTERNUMBER), v))
	})
}

// COUNTERNUMBERContainsFold applies the ContainsFold predicate on the "COUNTER_NUMBER" field.
func COUNTERNUMBERContainsFold(v string) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCOUNTERNUMBER), v))
	})
}

// HasFrom applies the HasEdge predicate on the "from" edge.
func HasFrom() predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromTable, FromColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromWith applies the HasEdge predicate on the "from" edge with a given conditions (other predicates).
func HasFromWith(preds ...predicate.Bookborrow) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromTable, FromColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServicepoint applies the HasEdge predicate on the "servicepoint" edge.
func HasServicepoint() predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ServicepointTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ServicepointTable, ServicepointColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServicepointWith applies the HasEdge predicate on the "servicepoint" edge with a given conditions (other predicates).
func HasServicepointWith(preds ...predicate.Booking) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ServicepointInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ServicepointTable, ServicepointColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.ServicePoint) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.ServicePoint) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServicePoint) predicate.ServicePoint {
	return predicate.ServicePoint(func(s *sql.Selector) {
		p(s.Not())
	})
}
