/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBookreturn
 */
export interface ControllersBookreturn {
    /**
     * 
     * @type {number}
     * @memberof ControllersBookreturn
     */
    bookborrowID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBookreturn
     */
    deadline?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBookreturn
     */
    locationID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBookreturn
     */
    userID?: number;
}

export function ControllersBookreturnFromJSON(json: any): ControllersBookreturn {
    return ControllersBookreturnFromJSONTyped(json, false);
}

export function ControllersBookreturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBookreturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookborrowID': !exists(json, 'bookborrowID') ? undefined : json['bookborrowID'],
        'deadline': !exists(json, 'deadline') ? undefined : json['deadline'],
        'locationID': !exists(json, 'locationID') ? undefined : json['locationID'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function ControllersBookreturnToJSON(value?: ControllersBookreturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookborrowID': value.bookborrowID,
        'deadline': value.deadline,
        'locationID': value.locationID,
        'userID': value.userID,
    };
}


