/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAuthorEdges,
    EntAuthorEdgesFromJSON,
    EntAuthorEdgesFromJSONTyped,
    EntAuthorEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAuthor
 */
export interface EntAuthor {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntAuthor
     */
    name?: string;
    /**
     * 
     * @type {EntAuthorEdges}
     * @memberof EntAuthor
     */
    edges?: EntAuthorEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntAuthor
     */
    id?: number;
}

export function EntAuthorFromJSON(json: any): EntAuthor {
    return EntAuthorFromJSONTyped(json, false);
}

export function EntAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntAuthorEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntAuthorToJSON(value?: EntAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntAuthorEdgesToJSON(value.edges),
        'id': value.id,
    };
}


