/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookingEdges,
    EntBookingEdgesFromJSON,
    EntBookingEdgesFromJSONTyped,
    EntBookingEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBooking
 */
export interface EntBooking {
    /**
     * BOOKINGDATE holds the value of the "BOOKING_DATE" field.
     * @type {string}
     * @memberof EntBooking
     */
    bOOKINGDATE?: string;
    /**
     * TIMELEFT holds the value of the "TIME_LEFT" field.
     * @type {string}
     * @memberof EntBooking
     */
    tIMELEFT?: string;
    /**
     * 
     * @type {number}
     * @memberof EntBooking
     */
    clientID?: number;
    /**
     * 
     * @type {EntBookingEdges}
     * @memberof EntBooking
     */
    edges?: EntBookingEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBooking
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBooking
     */
    servicepointID?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBooking
     */
    userID?: number;
}

export function EntBookingFromJSON(json: any): EntBooking {
    return EntBookingFromJSONTyped(json, false);
}

export function EntBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBooking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bOOKINGDATE': !exists(json, 'BOOKING_DATE') ? undefined : json['BOOKING_DATE'],
        'tIMELEFT': !exists(json, 'TIME_LEFT') ? undefined : json['TIME_LEFT'],
        'clientID': !exists(json, 'client_ID') ? undefined : json['client_ID'],
        'edges': !exists(json, 'edges') ? undefined : EntBookingEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'servicepointID': !exists(json, 'servicepoint_ID') ? undefined : json['servicepoint_ID'],
        'userID': !exists(json, 'user_ID') ? undefined : json['user_ID'],
    };
}

export function EntBookingToJSON(value?: EntBooking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BOOKING_DATE': value.bOOKINGDATE,
        'TIME_LEFT': value.tIMELEFT,
        'client_ID': value.clientID,
        'edges': EntBookingEdgesToJSON(value.edges),
        'id': value.id,
        'servicepoint_ID': value.servicepointID,
        'user_ID': value.userID,
    };
}


