/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookborrowEdges,
    EntBookborrowEdgesFromJSON,
    EntBookborrowEdgesFromJSONTyped,
    EntBookborrowEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookborrow
 */
export interface EntBookborrow {
    /**
     * BORROWDATE holds the value of the "BORROW_DATE" field.
     * @type {string}
     * @memberof EntBookborrow
     */
    bORROWDATE?: string;
    /**
     * 
     * @type {number}
     * @memberof EntBookborrow
     */
    bookID?: number;
    /**
     * 
     * @type {EntBookborrowEdges}
     * @memberof EntBookborrow
     */
    edges?: EntBookborrowEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBookborrow
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBookborrow
     */
    servicepointID?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBookborrow
     */
    userID?: number;
}

export function EntBookborrowFromJSON(json: any): EntBookborrow {
    return EntBookborrowFromJSONTyped(json, false);
}

export function EntBookborrowFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookborrow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bORROWDATE': !exists(json, 'BORROW_DATE') ? undefined : json['BORROW_DATE'],
        'bookID': !exists(json, 'book_ID') ? undefined : json['book_ID'],
        'edges': !exists(json, 'edges') ? undefined : EntBookborrowEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'servicepointID': !exists(json, 'servicepoint_ID') ? undefined : json['servicepoint_ID'],
        'userID': !exists(json, 'user_ID') ? undefined : json['user_ID'],
    };
}

export function EntBookborrowToJSON(value?: EntBookborrow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BORROW_DATE': value.bORROWDATE,
        'book_ID': value.bookID,
        'edges': EntBookborrowEdgesToJSON(value.edges),
        'id': value.id,
        'servicepoint_ID': value.servicepointID,
        'user_ID': value.userID,
    };
}


