/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookreturnEdges,
    EntBookreturnEdgesFromJSON,
    EntBookreturnEdgesFromJSONTyped,
    EntBookreturnEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookreturn
 */
export interface EntBookreturn {
    /**
     * RETURNTIME holds the value of the "RETURN_TIME" field.
     * @type {string}
     * @memberof EntBookreturn
     */
    rETURNTIME?: string;
    /**
     * 
     * @type {number}
     * @memberof EntBookreturn
     */
    clientID?: number;
    /**
     * 
     * @type {EntBookreturnEdges}
     * @memberof EntBookreturn
     */
    edges?: EntBookreturnEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBookreturn
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBookreturn
     */
    locationID?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBookreturn
     */
    userID?: number;
}

export function EntBookreturnFromJSON(json: any): EntBookreturn {
    return EntBookreturnFromJSONTyped(json, false);
}

export function EntBookreturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookreturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rETURNTIME': !exists(json, 'RETURN_TIME') ? undefined : json['RETURN_TIME'],
        'clientID': !exists(json, 'client_ID') ? undefined : json['client_ID'],
        'edges': !exists(json, 'edges') ? undefined : EntBookreturnEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'locationID': !exists(json, 'location_ID') ? undefined : json['location_ID'],
        'userID': !exists(json, 'user_ID') ? undefined : json['user_ID'],
    };
}

export function EntBookreturnToJSON(value?: EntBookreturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RETURN_TIME': value.rETURNTIME,
        'client_ID': value.clientID,
        'edges': EntBookreturnEdgesToJSON(value.edges),
        'id': value.id,
        'location_ID': value.locationID,
        'user_ID': value.userID,
    };
}


