/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntClientEntity,
    EntClientEntityFromJSON,
    EntClientEntityFromJSONTyped,
    EntClientEntityToJSON,
    EntServicePoint,
    EntServicePointFromJSON,
    EntServicePointFromJSONTyped,
    EntServicePointToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookingEdges
 */
export interface EntBookingEdges {
    /**
     * 
     * @type {EntServicePoint}
     * @memberof EntBookingEdges
     */
    getservice?: EntServicePoint;
    /**
     * 
     * @type {EntUser}
     * @memberof EntBookingEdges
     */
    usedby?: EntUser;
    /**
     * 
     * @type {EntClientEntity}
     * @memberof EntBookingEdges
     */
    using?: EntClientEntity;
}

export function EntBookingEdgesFromJSON(json: any): EntBookingEdges {
    return EntBookingEdgesFromJSONTyped(json, false);
}

export function EntBookingEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookingEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'getservice': !exists(json, 'Getservice') ? undefined : EntServicePointFromJSON(json['Getservice']),
        'usedby': !exists(json, 'Usedby') ? undefined : EntUserFromJSON(json['Usedby']),
        'using': !exists(json, 'Using') ? undefined : EntClientEntityFromJSON(json['Using']),
    };
}

export function EntBookingEdgesToJSON(value?: EntBookingEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'getservice': EntServicePointToJSON(value.getservice),
        'usedby': EntUserToJSON(value.usedby),
        'using': EntClientEntityToJSON(value.using),
    };
}


