/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPreemption,
    EntPreemptionFromJSON,
    EntPreemptionFromJSONTyped,
    EntPreemptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPurposeEdges
 */
export interface EntPurposeEdges {
    /**
     * Preemption holds the value of the preemption edge.
     * @type {Array<EntPreemption>}
     * @memberof EntPurposeEdges
     */
    preemption?: Array<EntPreemption>;
}

export function EntPurposeEdgesFromJSON(json: any): EntPurposeEdges {
    return EntPurposeEdgesFromJSONTyped(json, false);
}

export function EntPurposeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPurposeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preemption': !exists(json, 'preemption') ? undefined : ((json['preemption'] as Array<any>).map(EntPreemptionFromJSON)),
    };
}

export function EntPurposeEdgesToJSON(value?: EntPurposeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'preemption': value.preemption === undefined ? undefined : ((value.preemption as Array<any>).map(EntPreemptionToJSON)),
    };
}


