/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookborrow,
    EntBookborrowFromJSON,
    EntBookborrowFromJSONTyped,
    EntBookborrowToJSON,
    EntBooking,
    EntBookingFromJSON,
    EntBookingFromJSONTyped,
    EntBookingToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntServicePointEdges
 */
export interface EntServicePointEdges {
    /**
     * From holds the value of the from edge.
     * @type {Array<EntBookborrow>}
     * @memberof EntServicePointEdges
     */
    from?: Array<EntBookborrow>;
    /**
     * Servicepoint holds the value of the servicepoint edge.
     * @type {Array<EntBooking>}
     * @memberof EntServicePointEdges
     */
    servicepoint?: Array<EntBooking>;
}

export function EntServicePointEdgesFromJSON(json: any): EntServicePointEdges {
    return EntServicePointEdgesFromJSONTyped(json, false);
}

export function EntServicePointEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntServicePointEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : ((json['from'] as Array<any>).map(EntBookborrowFromJSON)),
        'servicepoint': !exists(json, 'servicepoint') ? undefined : ((json['servicepoint'] as Array<any>).map(EntBookingFromJSON)),
    };
}

export function EntServicePointEdgesToJSON(value?: EntServicePointEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from === undefined ? undefined : ((value.from as Array<any>).map(EntBookborrowToJSON)),
        'servicepoint': value.servicepoint === undefined ? undefined : ((value.servicepoint as Array<any>).map(EntBookingToJSON)),
    };
}


