// Code generated by entc, DO NOT EDIT.

package cliententity

const (
	// Label holds the string label denoting the cliententity type in the database.
	Label = "client_entity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCLIENTNAME holds the string denoting the client_name field in the database.
	FieldCLIENTNAME = "client_name"

	// EdgeBooked holds the string denoting the booked edge name in mutations.
	EdgeBooked = "booked"
	// EdgeState holds the string denoting the state edge name in mutations.
	EdgeState = "state"

	// Table holds the table name of the cliententity in the database.
	Table = "client_entities"
	// BookedTable is the table the holds the booked relation/edge.
	BookedTable = "bookings"
	// BookedInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookedInverseTable = "bookings"
	// BookedColumn is the table column denoting the booked relation/edge.
	BookedColumn = "CLIENT_ID"
	// StateTable is the table the holds the state relation/edge.
	StateTable = "client_entities"
	// StateInverseTable is the table name for the Status entity.
	// It exists in this package in order to avoid circular dependency with the "status" package.
	StateInverseTable = "status"
	// StateColumn is the table column denoting the state relation/edge.
	StateColumn = "STATUS_ID"
)

// Columns holds all SQL columns for cliententity fields.
var Columns = []string{
	FieldID,
	FieldCLIENTNAME,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the ClientEntity type.
var ForeignKeys = []string{
	"STATUS_ID",
}

var (
	// CLIENTNAMEValidator is a validator for the "CLIENT_NAME" field. It is called by the builders before save.
	CLIENTNAMEValidator func(string) error
)
